services:
  app:
    build: .
    depends_on:
      - db
    container_name: fastapi-development
    ports:
      - 5050:5050
    volumes:
      - ./app:/app
  db:
    image: postgres
    container_name: postgres-development
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fastapi_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data